on:
  workflow_dispatch:

jobs:
  Publish-Addon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - uses: trmcnvn/firefox-addon@v1
        with:
          uuid: '{marcel@feixe.de}'
          xpi: build/my-addon.xpi
          manifest: manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}
